### ISSUE TITLE
npm i提示缺少文件

### ISSUE THREAD

**Issue by catnfish** [lxrmido/WordCards#2]
win7，clone到wc目录后提示缺少如下文件
c:\wc>npm i
npm WARN tar ENOENT: no such file or directory, open 'c:\wc\node_modules\.stagin
g\qs-foobar\lib\formats.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\wc\node_modules\.stagin
g\qs-foobar\lib\index.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\wc\node_modules\.stagin
g\qs-foobar\lib\parse.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\wc\node_modules\.stagin
g\qs-foobar\lib\stringify.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\wc\node_modules\.stagin
g\qs-foobar\lib\utils.js'
npm WARN wc No repository field.
npm WARN wc No license field.

**Comment by catnfish** [comment]
尝试更换到linux系统，
npm i提示：
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN rollup-plugin-json@2.3.1 requires a peer of rollup@< 0.59.0 but none was installed.
npm WARN wordcard@1.0.0 No repository field.

node server提示：
module.js:549
    throw err;
    ^
Error: Cannot find module '/home/mint/wordcard/server'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

Error: Cannot find module '/home/mint/wordcard/server'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
